"""Added mobile field

Revision ID: 3b8464d608cc
Revises: 1cc61521a73d
Create Date: 2025-08-04 23:12:13.495354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b8464d608cc'
down_revision = '1cc61521a73d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_mobile'), ['mobile'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_mobile'))
        batch_op.drop_column('mobile')

    # ### end Alembic commands ###
